/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    articles: Article;
    'case-studies': CaseStudy;
    'site-pages': SitePage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    homepage: Homepage;
    footer: Footer;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Short blurb for listing cards (artykuły grid).
   */
  summary?: string | null;
  /**
   * Longer lead under the article title.
   */
  excerpt?: string | null;
  /**
   * Article detail — e.g. Metodyka
   */
  categoryLabel?: string | null;
  /**
   * Article detail — e.g. reading time line
   */
  categoryMeta?: string | null;
  /**
   * Listing card — e.g. 12 min czytania
   */
  readingTime?: string | null;
  category: 'methodology' | 'management' | 'case_studies';
  tone?: ('light' | 'dark' | 'accent') | null;
  keyTakeaway?: {
    heading?: string | null;
    body?: string | null;
  };
  sections?:
    | {
        id: string;
        number?: string | null;
        label?: string | null;
        title?: string | null;
        contentFormat?: ('plain' | 'html') | null;
        /**
         * Plain: paragraphs separated by blank lines; ## / ### headings. HTML: trusted markup.
         */
        content?: string | null;
      }[]
    | null;
  relatedArticles?: (number | Article)[] | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  excerpt?: string | null;
  results?: string | null;
  heroImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One document per route (szkolenia, hiring, useme, articles). Layout drives page sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  routeKey: 'szkolenia' | 'hiring' | 'useme' | 'articles';
  /**
   * Stack sections top-to-bottom.
   */
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            intro?: string | null;
            /**
             * Small label above KPI column (optional)
             */
            asideEyebrow?: string | null;
            asideStats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Timeline-style aside when stats empty (e.g. 2024)
             */
            asidePrimary?: string | null;
            /**
             * Subtitle under asidePrimary (e.g. project timeline)
             */
            asideSecondary?: string | null;
            /**
             * Accessibility label on aside (hiring KPI / useme timeline)
             */
            asideAriaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBand';
          }
        | {
            sectionTitle: string;
            sectionEyebrow?: string | null;
            jobs?:
              | {
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  compensation?: string | null;
                  location?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'jobGrid';
          }
        | {
            title: string;
            intro?: string | null;
            steps?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Decorative gradient placeholder next to intro
             */
            showPlaceholder?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processGrid';
          }
        | {
            headingTitle: string;
            headingEyebrow?: string | null;
            modules?:
              | {
                  number?: string | null;
                  title: string;
                  body?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  variant?: ('light' | 'dark' | 'accent') | null;
                  /**
                   * Szkolenia wide module: aside label (e.g. KEY TAKEAWAY)
                   */
                  asideEyebrow?: string | null;
                  /**
                   * Two lines separated by newline (wide module quote)
                   */
                  asideQuote?: string | null;
                  /**
                   * Szkolenia accent module: decorative strip image URL
                   */
                  footerImageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programModules';
          }
        | {
            sectionTitle?: string | null;
            sectionSubtitle?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            /**
             * Hero image URL (optional)
             */
            mediaUrl?: string | null;
            leftTitle: string;
            bodyParagraphs: string;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richSplit';
          }
        | {
            title: string;
            features?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengeBand';
          }
        | {
            title: string;
            features?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            verdictBadge?: string | null;
            verdictBody: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengeVerdictSplit';
          }
        | {
            headingTitle: string;
            headingSubtitle?: string | null;
            columns?:
              | {
                  iconUrl?: string | null;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureColumns3';
          }
        | {
            lightCard: {
              quote: string;
              authorName: string;
              role: string;
              avatarInitials?: string | null;
            };
            darkCardTop: {
              quote: string;
              authorName: string;
              role: string;
            };
            darkCardBottom: {
              quote: string;
              authorName: string;
              role: string;
            };
            statCell: {
              value: string;
              label: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'usemeBentoResults';
          }
        | {
            headingTitle: string;
            headingEyebrow?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsRow4';
          }
        | {
            eyebrow: string;
            title: string;
            intro: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articlesHero';
          }
        | {
            /**
             * Trusted HTML injected after sanitization expectation — editors only.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'htmlSnippet';
          }
        | {
            sectionTitle: string;
            tiles?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methodTileGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            pillars?:
              | {
                  title: string;
                  iconUrl?: string | null;
                  clients?:
                    | {
                        name: string;
                        segment: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industryPillars';
          }
        | {
            badge?: string | null;
            title: string;
            ctaLabel?: string | null;
            ctaPath?: string | null;
            metrics?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseHighlightCta';
          }
        | {
            sectionTitle: string;
            steps?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberedIconSteps';
          }
        | {
            eyebrow?: string | null;
            name: string;
            bodyParagraphs: string;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            portraitUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founderSpotlight';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  role: string;
                  avatarUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsHome';
          }
        | {
            /**
             * Włączone: karty z Globals → Homepage → Baza wiedzy (wybrane artykuły, max 3). Wyłączone: użyj ręcznych kart poniżej.
             */
            useHomepageFeaturedArticles?: boolean | null;
            eyebrow?: string | null;
            heading: string;
            subtitle?: string | null;
            cards?:
              | {
                  categoryLabel?: string | null;
                  title: string;
                  excerpt?: string | null;
                  imageUrl?: string | null;
                  href?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'knowledgeTeasers';
          }
        | {
            titleLine1: string;
            titleLine2: string;
            /**
             * Four lines, newline-separated
             */
            intro: string;
            benefit1: string;
            benefit2: string;
            benefit3: string;
            statValue: string;
            statLabel: string;
            /**
             * Three lines, newline-separated
             */
            quote: string;
            darkCardTitle: string;
            darkCardBody: string;
            /**
             * Obraz w prawym dolnym kafelku (zamiast zielonego pola). Opcjonalny — bez pliku zostaje układ demonstracyjny.
             */
            accentTileImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'szkoleniaWhyShapeUp';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'site-pages';
        value: number | SitePage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  summary?: T;
  excerpt?: T;
  categoryLabel?: T;
  categoryMeta?: T;
  readingTime?: T;
  category?: T;
  tone?: T;
  keyTakeaway?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  sections?:
    | T
    | {
        id?: T;
        number?: T;
        label?: T;
        title?: T;
        contentFormat?: T;
        content?: T;
      };
  relatedArticles?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  excerpt?: T;
  results?: T;
  heroImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  routeKey?: T;
  layout?:
    | T
    | {
        heroBand?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              asideEyebrow?: T;
              asideStats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              asidePrimary?: T;
              asideSecondary?: T;
              asideAriaLabel?: T;
              id?: T;
              blockName?: T;
            };
        jobGrid?:
          | T
          | {
              sectionTitle?: T;
              sectionEyebrow?: T;
              jobs?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    compensation?: T;
                    location?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processGrid?:
          | T
          | {
              title?: T;
              intro?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              id?: T;
              blockName?: T;
            };
        programModules?:
          | T
          | {
              headingTitle?: T;
              headingEyebrow?: T;
              modules?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    variant?: T;
                    asideEyebrow?: T;
                    asideQuote?: T;
                    footerImageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              sectionTitle?: T;
              sectionSubtitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richSplit?:
          | T
          | {
              mediaUrl?: T;
              leftTitle?: T;
              bodyParagraphs?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        challengeBand?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        challengeVerdictSplit?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              verdictBadge?: T;
              verdictBody?: T;
              id?: T;
              blockName?: T;
            };
        featureColumns3?:
          | T
          | {
              headingTitle?: T;
              headingSubtitle?: T;
              columns?:
                | T
                | {
                    iconUrl?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        usemeBentoResults?:
          | T
          | {
              lightCard?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                    avatarInitials?: T;
                  };
              darkCardTop?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                  };
              darkCardBottom?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                  };
              statCell?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsRow4?:
          | T
          | {
              headingTitle?: T;
              headingEyebrow?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        articlesHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        htmlSnippet?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        methodTileGrid?:
          | T
          | {
              sectionTitle?: T;
              tiles?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industryPillars?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    iconUrl?: T;
                    clients?:
                      | T
                      | {
                          name?: T;
                          segment?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseHighlightCta?:
          | T
          | {
              badge?: T;
              title?: T;
              ctaLabel?: T;
              ctaPath?: T;
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numberedIconSteps?:
          | T
          | {
              sectionTitle?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founderSpotlight?:
          | T
          | {
              eyebrow?: T;
              name?: T;
              bodyParagraphs?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              portraitUrl?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsHome?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                    avatarUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        knowledgeTeasers?:
          | T
          | {
              useHomepageFeaturedArticles?: T;
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    categoryLabel?: T;
                    title?: T;
                    excerpt?: T;
                    imageUrl?: T;
                    href?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        szkoleniaWhyShapeUp?:
          | T
          | {
              titleLine1?: T;
              titleLine2?: T;
              intro?: T;
              benefit1?: T;
              benefit2?: T;
              benefit3?: T;
              statValue?: T;
              statLabel?: T;
              quote?: T;
              darkCardTitle?: T;
              darkCardBody?: T;
              accentTileImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  links?:
    | {
        label: string;
        /**
         * React Router path, e.g. /artykuly
         */
        path: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  /**
   * CTA target — e.g. /#konsultacja for in-page scroll
   */
  ctaPath?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Text before the accent word (e.g. Odzyskaj kontrolę nad)
   */
  heroHeadlinePrefix?: string | null;
  /**
   * Gradient accent word (e.g. RoadMapą!)
   */
  heroHeadlineAccent?: string | null;
  heroSubheadline?: string | null;
  heroCtaLabel?: string | null;
  /**
   * Usually /#konsultacja
   */
  heroCtaPath?: string | null;
  heroImage?: (number | null) | Media;
  servicesEyebrow?: string | null;
  servicesHeading?: string | null;
  servicesIntro?: string | null;
  services?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Optional icon URL or asset path
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutHeading?: string | null;
  /**
   * About section copy (plain text or trusted HTML if the site renders it).
   */
  aboutBody?: string | null;
  /**
   * Default: "Jak pomagam"
   */
  expertiseEyebrow?: string | null;
  /**
   * Default: "Obszary ekspertyzy"
   */
  expertiseHeading?: string | null;
  /**
   * Paragraphs separated by blank lines
   */
  expertiseIntro?: string | null;
  expertiseItems?:
    | {
        /**
         * e.g. 01
         */
        number?: string | null;
        title: string;
        layout?: ('simple' | 'bullets') | null;
        /**
         * Shown when layout is simple or as intro with bullets
         */
        body?: string | null;
        bullets?:
          | {
              line: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "know-how"
   */
  communityHeadlineItalic?: string | null;
  /**
   * e.g. "by community"
   */
  communityHeadlineRest?: string | null;
  communityLeadBold?: string | null;
  communityBody?: string | null;
  communitySupportingBrands?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  communityExpertNames?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tła sekcji community (karuzela). Upload z biblioteki Media — gdy dodasz przynajmniej jedno zdjęcie, lista adresów URL poniżej jest pomijana.
   */
  communityBackgroundPhotos?: (number | Media)[] | null;
  /**
   * Opcjonalnie: zewnętrzne adresy URL obrazów (starszy sposób). Używane tylko gdy „Community background photos” jest puste.
   */
  communityBgUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  methodologyEyebrow?: string | null;
  methodologyHeading?: string | null;
  /**
   * Separate paragraphs with blank lines
   */
  methodologyParagraphs?: string | null;
  /**
   * Icon rows (Tailored solutions, Step-by-step…)
   */
  methodologyBullets?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy optional blocks immediately after methodology. Prefer „Home continuation layout” for the rest of the page.
   */
  homeTailLayout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            intro?: string | null;
            /**
             * Small label above KPI column (optional)
             */
            asideEyebrow?: string | null;
            asideStats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Timeline-style aside when stats empty (e.g. 2024)
             */
            asidePrimary?: string | null;
            /**
             * Subtitle under asidePrimary (e.g. project timeline)
             */
            asideSecondary?: string | null;
            /**
             * Accessibility label on aside (hiring KPI / useme timeline)
             */
            asideAriaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBand';
          }
        | {
            sectionTitle: string;
            sectionEyebrow?: string | null;
            jobs?:
              | {
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  compensation?: string | null;
                  location?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'jobGrid';
          }
        | {
            title: string;
            intro?: string | null;
            steps?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Decorative gradient placeholder next to intro
             */
            showPlaceholder?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processGrid';
          }
        | {
            headingTitle: string;
            headingEyebrow?: string | null;
            modules?:
              | {
                  number?: string | null;
                  title: string;
                  body?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  variant?: ('light' | 'dark' | 'accent') | null;
                  /**
                   * Szkolenia wide module: aside label (e.g. KEY TAKEAWAY)
                   */
                  asideEyebrow?: string | null;
                  /**
                   * Two lines separated by newline (wide module quote)
                   */
                  asideQuote?: string | null;
                  /**
                   * Szkolenia accent module: decorative strip image URL
                   */
                  footerImageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programModules';
          }
        | {
            sectionTitle?: string | null;
            sectionSubtitle?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            /**
             * Hero image URL (optional)
             */
            mediaUrl?: string | null;
            leftTitle: string;
            bodyParagraphs: string;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richSplit';
          }
        | {
            title: string;
            features?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengeBand';
          }
        | {
            title: string;
            features?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            verdictBadge?: string | null;
            verdictBody: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengeVerdictSplit';
          }
        | {
            headingTitle: string;
            headingSubtitle?: string | null;
            columns?:
              | {
                  iconUrl?: string | null;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureColumns3';
          }
        | {
            lightCard: {
              quote: string;
              authorName: string;
              role: string;
              avatarInitials?: string | null;
            };
            darkCardTop: {
              quote: string;
              authorName: string;
              role: string;
            };
            darkCardBottom: {
              quote: string;
              authorName: string;
              role: string;
            };
            statCell: {
              value: string;
              label: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'usemeBentoResults';
          }
        | {
            headingTitle: string;
            headingEyebrow?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsRow4';
          }
        | {
            eyebrow: string;
            title: string;
            intro: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articlesHero';
          }
        | {
            /**
             * Trusted HTML injected after sanitization expectation — editors only.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'htmlSnippet';
          }
        | {
            sectionTitle: string;
            tiles?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methodTileGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            pillars?:
              | {
                  title: string;
                  iconUrl?: string | null;
                  clients?:
                    | {
                        name: string;
                        segment: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industryPillars';
          }
        | {
            badge?: string | null;
            title: string;
            ctaLabel?: string | null;
            ctaPath?: string | null;
            metrics?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseHighlightCta';
          }
        | {
            sectionTitle: string;
            steps?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberedIconSteps';
          }
        | {
            eyebrow?: string | null;
            name: string;
            bodyParagraphs: string;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            portraitUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founderSpotlight';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  role: string;
                  avatarUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsHome';
          }
        | {
            /**
             * Włączone: karty z Globals → Homepage → Baza wiedzy (wybrane artykuły, max 3). Wyłączone: użyj ręcznych kart poniżej.
             */
            useHomepageFeaturedArticles?: boolean | null;
            eyebrow?: string | null;
            heading: string;
            subtitle?: string | null;
            cards?:
              | {
                  categoryLabel?: string | null;
                  title: string;
                  excerpt?: string | null;
                  imageUrl?: string | null;
                  href?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'knowledgeTeasers';
          }
        | {
            titleLine1: string;
            titleLine2: string;
            /**
             * Four lines, newline-separated
             */
            intro: string;
            benefit1: string;
            benefit2: string;
            benefit3: string;
            statValue: string;
            statLabel: string;
            /**
             * Three lines, newline-separated
             */
            quote: string;
            darkCardTitle: string;
            darkCardBody: string;
            /**
             * Obraz w prawym dolnym kafelku (zamiast zielonego pola). Opcjonalny — bez pliku zostaje układ demonstracyjny.
             */
            accentTileImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'szkoleniaWhyShapeUp';
          }
      )[]
    | null;
  /**
   * Ordered sections from practice tiles through knowledge grid (method tiles, pillars, founder, testimonials, article teasers, etc.).
   */
  homeContinuationLayout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            intro?: string | null;
            /**
             * Small label above KPI column (optional)
             */
            asideEyebrow?: string | null;
            asideStats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Timeline-style aside when stats empty (e.g. 2024)
             */
            asidePrimary?: string | null;
            /**
             * Subtitle under asidePrimary (e.g. project timeline)
             */
            asideSecondary?: string | null;
            /**
             * Accessibility label on aside (hiring KPI / useme timeline)
             */
            asideAriaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBand';
          }
        | {
            sectionTitle: string;
            sectionEyebrow?: string | null;
            jobs?:
              | {
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  compensation?: string | null;
                  location?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'jobGrid';
          }
        | {
            title: string;
            intro?: string | null;
            steps?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Decorative gradient placeholder next to intro
             */
            showPlaceholder?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processGrid';
          }
        | {
            headingTitle: string;
            headingEyebrow?: string | null;
            modules?:
              | {
                  number?: string | null;
                  title: string;
                  body?: string | null;
                  tags?:
                    | {
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  variant?: ('light' | 'dark' | 'accent') | null;
                  /**
                   * Szkolenia wide module: aside label (e.g. KEY TAKEAWAY)
                   */
                  asideEyebrow?: string | null;
                  /**
                   * Two lines separated by newline (wide module quote)
                   */
                  asideQuote?: string | null;
                  /**
                   * Szkolenia accent module: decorative strip image URL
                   */
                  footerImageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programModules';
          }
        | {
            sectionTitle?: string | null;
            sectionSubtitle?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqList';
          }
        | {
            /**
             * Hero image URL (optional)
             */
            mediaUrl?: string | null;
            leftTitle: string;
            bodyParagraphs: string;
            quote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richSplit';
          }
        | {
            title: string;
            features?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengeBand';
          }
        | {
            title: string;
            features?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            verdictBadge?: string | null;
            verdictBody: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengeVerdictSplit';
          }
        | {
            headingTitle: string;
            headingSubtitle?: string | null;
            columns?:
              | {
                  iconUrl?: string | null;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureColumns3';
          }
        | {
            lightCard: {
              quote: string;
              authorName: string;
              role: string;
              avatarInitials?: string | null;
            };
            darkCardTop: {
              quote: string;
              authorName: string;
              role: string;
            };
            darkCardBottom: {
              quote: string;
              authorName: string;
              role: string;
            };
            statCell: {
              value: string;
              label: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'usemeBentoResults';
          }
        | {
            headingTitle: string;
            headingEyebrow?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsRow4';
          }
        | {
            eyebrow: string;
            title: string;
            intro: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articlesHero';
          }
        | {
            /**
             * Trusted HTML injected after sanitization expectation — editors only.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'htmlSnippet';
          }
        | {
            sectionTitle: string;
            tiles?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methodTileGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            pillars?:
              | {
                  title: string;
                  iconUrl?: string | null;
                  clients?:
                    | {
                        name: string;
                        segment: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industryPillars';
          }
        | {
            badge?: string | null;
            title: string;
            ctaLabel?: string | null;
            ctaPath?: string | null;
            metrics?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseHighlightCta';
          }
        | {
            sectionTitle: string;
            steps?:
              | {
                  number: string;
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberedIconSteps';
          }
        | {
            eyebrow?: string | null;
            name: string;
            bodyParagraphs: string;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            portraitUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'founderSpotlight';
          }
        | {
            sectionTitle?: string | null;
            items?:
              | {
                  quote: string;
                  authorName: string;
                  role: string;
                  avatarUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsHome';
          }
        | {
            /**
             * Włączone: karty z Globals → Homepage → Baza wiedzy (wybrane artykuły, max 3). Wyłączone: użyj ręcznych kart poniżej.
             */
            useHomepageFeaturedArticles?: boolean | null;
            eyebrow?: string | null;
            heading: string;
            subtitle?: string | null;
            cards?:
              | {
                  categoryLabel?: string | null;
                  title: string;
                  excerpt?: string | null;
                  imageUrl?: string | null;
                  href?: string | null;
                  ctaLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'knowledgeTeasers';
          }
        | {
            titleLine1: string;
            titleLine2: string;
            /**
             * Four lines, newline-separated
             */
            intro: string;
            benefit1: string;
            benefit2: string;
            benefit3: string;
            statValue: string;
            statLabel: string;
            /**
             * Three lines, newline-separated
             */
            quote: string;
            darkCardTitle: string;
            darkCardBody: string;
            /**
             * Obraz w prawym dolnym kafelku (zamiast zielonego pola). Opcjonalny — bez pliku zostaje układ demonstracyjny.
             */
            accentTileImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'szkoleniaWhyShapeUp';
          }
      )[]
    | null;
  /**
   * Portret w sekcji „Architekt projektu” / Dawid Jurand Szkiełka — zaokrąglony prawy górny róg nadal z CSS. Bez uploadu pokazywany jest domyślny obraz z layoutu.
   */
  founderPortrait?: (number | null) | Media;
  /**
   * Krótki opis dla a11y (np. Dawid Jurand Szkiełka, portret)
   */
  founderPortraitAlt?: string | null;
  /**
   * Maks. 3 opublikowane artykuły — kolejność tu = kolejność kafelków. Używane gdy blok „Knowledge teaser grid” ma włączone „Użyj wyboru ze strony głównej”, oraz na stronie głównej bez bloków CMS.
   */
  featuredKnowledgeArticles?: (number | Article)[] | null;
  contactEyebrow?: string | null;
  contactHeading?: string | null;
  contactIntro?: string | null;
  contactEmail?: string | null;
  contactLocation?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  companyName?: string | null;
  tagline?: string | null;
  email?: string | null;
  linkedinUrl?: string | null;
  legalText?: string | null;
  /**
   * Four columns like current footer
   */
  columns?:
    | {
        title: string;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  siteName?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaPath?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeadlinePrefix?: T;
  heroHeadlineAccent?: T;
  heroSubheadline?: T;
  heroCtaLabel?: T;
  heroCtaPath?: T;
  heroImage?: T;
  servicesEyebrow?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  aboutHeading?: T;
  aboutBody?: T;
  expertiseEyebrow?: T;
  expertiseHeading?: T;
  expertiseIntro?: T;
  expertiseItems?:
    | T
    | {
        number?: T;
        title?: T;
        layout?: T;
        body?: T;
        bullets?:
          | T
          | {
              line?: T;
              id?: T;
            };
        id?: T;
      };
  communityHeadlineItalic?: T;
  communityHeadlineRest?: T;
  communityLeadBold?: T;
  communityBody?: T;
  communitySupportingBrands?:
    | T
    | {
        name?: T;
        id?: T;
      };
  communityExpertNames?:
    | T
    | {
        name?: T;
        id?: T;
      };
  communityBackgroundPhotos?: T;
  communityBgUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  methodologyEyebrow?: T;
  methodologyHeading?: T;
  methodologyParagraphs?: T;
  methodologyBullets?:
    | T
    | {
        title?: T;
        id?: T;
      };
  homeTailLayout?:
    | T
    | {
        heroBand?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              asideEyebrow?: T;
              asideStats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              asidePrimary?: T;
              asideSecondary?: T;
              asideAriaLabel?: T;
              id?: T;
              blockName?: T;
            };
        jobGrid?:
          | T
          | {
              sectionTitle?: T;
              sectionEyebrow?: T;
              jobs?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    compensation?: T;
                    location?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processGrid?:
          | T
          | {
              title?: T;
              intro?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              id?: T;
              blockName?: T;
            };
        programModules?:
          | T
          | {
              headingTitle?: T;
              headingEyebrow?: T;
              modules?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    variant?: T;
                    asideEyebrow?: T;
                    asideQuote?: T;
                    footerImageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              sectionTitle?: T;
              sectionSubtitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richSplit?:
          | T
          | {
              mediaUrl?: T;
              leftTitle?: T;
              bodyParagraphs?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        challengeBand?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        challengeVerdictSplit?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              verdictBadge?: T;
              verdictBody?: T;
              id?: T;
              blockName?: T;
            };
        featureColumns3?:
          | T
          | {
              headingTitle?: T;
              headingSubtitle?: T;
              columns?:
                | T
                | {
                    iconUrl?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        usemeBentoResults?:
          | T
          | {
              lightCard?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                    avatarInitials?: T;
                  };
              darkCardTop?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                  };
              darkCardBottom?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                  };
              statCell?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsRow4?:
          | T
          | {
              headingTitle?: T;
              headingEyebrow?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        articlesHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        htmlSnippet?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        methodTileGrid?:
          | T
          | {
              sectionTitle?: T;
              tiles?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industryPillars?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    iconUrl?: T;
                    clients?:
                      | T
                      | {
                          name?: T;
                          segment?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseHighlightCta?:
          | T
          | {
              badge?: T;
              title?: T;
              ctaLabel?: T;
              ctaPath?: T;
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numberedIconSteps?:
          | T
          | {
              sectionTitle?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founderSpotlight?:
          | T
          | {
              eyebrow?: T;
              name?: T;
              bodyParagraphs?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              portraitUrl?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsHome?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                    avatarUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        knowledgeTeasers?:
          | T
          | {
              useHomepageFeaturedArticles?: T;
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    categoryLabel?: T;
                    title?: T;
                    excerpt?: T;
                    imageUrl?: T;
                    href?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        szkoleniaWhyShapeUp?:
          | T
          | {
              titleLine1?: T;
              titleLine2?: T;
              intro?: T;
              benefit1?: T;
              benefit2?: T;
              benefit3?: T;
              statValue?: T;
              statLabel?: T;
              quote?: T;
              darkCardTitle?: T;
              darkCardBody?: T;
              accentTileImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  homeContinuationLayout?:
    | T
    | {
        heroBand?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              asideEyebrow?: T;
              asideStats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              asidePrimary?: T;
              asideSecondary?: T;
              asideAriaLabel?: T;
              id?: T;
              blockName?: T;
            };
        jobGrid?:
          | T
          | {
              sectionTitle?: T;
              sectionEyebrow?: T;
              jobs?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    compensation?: T;
                    location?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processGrid?:
          | T
          | {
              title?: T;
              intro?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              id?: T;
              blockName?: T;
            };
        programModules?:
          | T
          | {
              headingTitle?: T;
              headingEyebrow?: T;
              modules?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    tags?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    variant?: T;
                    asideEyebrow?: T;
                    asideQuote?: T;
                    footerImageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              sectionTitle?: T;
              sectionSubtitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richSplit?:
          | T
          | {
              mediaUrl?: T;
              leftTitle?: T;
              bodyParagraphs?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
        challengeBand?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        challengeVerdictSplit?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              verdictBadge?: T;
              verdictBody?: T;
              id?: T;
              blockName?: T;
            };
        featureColumns3?:
          | T
          | {
              headingTitle?: T;
              headingSubtitle?: T;
              columns?:
                | T
                | {
                    iconUrl?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        usemeBentoResults?:
          | T
          | {
              lightCard?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                    avatarInitials?: T;
                  };
              darkCardTop?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                  };
              darkCardBottom?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                  };
              statCell?:
                | T
                | {
                    value?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsRow4?:
          | T
          | {
              headingTitle?: T;
              headingEyebrow?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        articlesHero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        htmlSnippet?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        methodTileGrid?:
          | T
          | {
              sectionTitle?: T;
              tiles?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industryPillars?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    iconUrl?: T;
                    clients?:
                      | T
                      | {
                          name?: T;
                          segment?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseHighlightCta?:
          | T
          | {
              badge?: T;
              title?: T;
              ctaLabel?: T;
              ctaPath?: T;
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numberedIconSteps?:
          | T
          | {
              sectionTitle?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        founderSpotlight?:
          | T
          | {
              eyebrow?: T;
              name?: T;
              bodyParagraphs?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              portraitUrl?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsHome?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    role?: T;
                    avatarUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        knowledgeTeasers?:
          | T
          | {
              useHomepageFeaturedArticles?: T;
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    categoryLabel?: T;
                    title?: T;
                    excerpt?: T;
                    imageUrl?: T;
                    href?: T;
                    ctaLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        szkoleniaWhyShapeUp?:
          | T
          | {
              titleLine1?: T;
              titleLine2?: T;
              intro?: T;
              benefit1?: T;
              benefit2?: T;
              benefit3?: T;
              statValue?: T;
              statLabel?: T;
              quote?: T;
              darkCardTitle?: T;
              darkCardBody?: T;
              accentTileImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  founderPortrait?: T;
  founderPortraitAlt?: T;
  featuredKnowledgeArticles?: T;
  contactEyebrow?: T;
  contactHeading?: T;
  contactIntro?: T;
  contactEmail?: T;
  contactLocation?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  email?: T;
  linkedinUrl?: T;
  legalText?: T;
  columns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteName?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}